# Javascript Node CircleCI 2.0 configuration file
defaults: &defaults
  docker:
    - image: circleci/node:12.16.3-browsers
    - image: circleci/mysql:8.0.4
      environment:
        TEST_DATABASE_URL: mysql://root@localhost/circle_test
    - image: cypress/base:8

  working_directory: ~/MERNolithic_sql

version: 2
jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - run:
          name: Install general dependencies
          command: yarn install
      - run:
          name: Install frontend packages
          command: cd frontend && yarn install
      - run:
          name: Install backend packages
          command: cd backend && yarn install
      - run:
          name: Build frontend
          command: cd frontend && yarn build

  cypress_tests:
    <<: *defaults

    steps:
      - checkout
      - run:
          name: install general dependencies
          command: yarn install
      - run:
          name: install frontend dependencies
          command: cd frontend && yarn install
      - run:
          name: Run cypress tests
          command: yarn test:create-reports-local
      - run:
          name: Test coverage threshold
          command: yarn get-coverage
      - store_artifacts:
          path: coverage/lcov-report
      - store_artifacts:
          path: cypress/reports/integration/public/

workflows:
  version: 2
  starter-workflow:
    jobs:
      - build
      - cypress_tests:
          requires:
            - build
